{
    'name':        'Estate Rental',
    'version':     '18.0.1.0.0',
    'category':    'Real Estate',
    'summary':     'Rental management — Lease, Deposit, Maintenance, Utilities, Caretaker, Demand Notices',
    'author':      'Paul Nyoike',
    'website':     'https://github.com/NyoikePaul/OdooERP',
    'license':     'LGPL-3',
    'depends':     ['estate_core', 'mpesa_connector'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/cron.xml',
        'wizard/rent_invoice_wizard.xml',
        'wizard/lease_renewal_wizard.xml',
        'wizard/broadcast_wizard.xml',
        'views/lease_views.xml',
        'views/maintenance_views.xml',
        'views/operations_views.xml',
        'views/kenya_views.xml',
        'report/tenancy_agreement.xml',
        'report/rent_roll.xml',
        'report/demand_notice_report.xml',
        'views/menu_views.xml',
    ],
    'installable':  True,
    'application':  False,
    'auto_install': False,
}
