{
    'name':        'Kenya Real Estate CRM',
    'version':     '18.0.5.0.0',
    'category':    'Real Estate',
    'summary':     'Enterprise property management for East Africa — M-Pesa, KRA WHT, MRI Returns, Generator Billing, Demand Notices',
    'description': """
Kenya Real Estate CRM — Built for East Africa.
Solves KRA MRI compliance (April 2025), generator billing,
service charge apportionment, tenant screening, demand notices,
caretaker management, and M-Pesa rent collection.
    """,
    'author':      'Paul Nyoike',
    'maintainer':  'Paul Nyoike',
    'website':     'https://github.com/NyoikePaul/OdooERP',
    'license':     'LGPL-3',
    'depends':     ['base', 'account', 'mail', 'mpesa_connector'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/cron.xml',
        'views/property_type_views.xml',
        'views/property_views.xml',
        'views/building_views.xml',
        'views/lease_views.xml',
        'views/maintenance_views.xml',
        'views/operations_views.xml',
        'views/kenya_views.xml',
        'wizard/rent_invoice_wizard.xml',
        'wizard/lease_renewal_wizard.xml',
        'wizard/broadcast_wizard.xml',
        'report/tenancy_agreement.xml',
        'report/rent_roll.xml',
        'views/menu_views.xml',
    ],
    'demo':        ['demo/demo.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'images':      ['static/description/icon.svg'],
}
