{
    'name': 'Kenya Real Estate CRM',
    'version': '18.0.3.0.0',
    'category': 'Real Estate',
    'summary': 'Premium property management — Buildings, Units, Leases, Inspections, Deposits, Commissions, Utility Billing, M-Pesa',
    'author': 'Paul Nyoike - Nairobi',
    'website': 'https://github.com/NyoikePaul/OdooERP',
    'depends': ['base', 'account', 'mail', 'mpesa_connector'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/cron.xml',
        'views/config_views.xml',
        'views/property_views.xml',
        'views/lease_views.xml',
        'views/maintenance_views.xml',
        'views/premium_views.xml',
        'wizard/rent_payment_wizard.xml',
        'wizard/lease_renewal_wizard.xml',
        'report/lease_report.xml',
        'views/menu_views.xml',
        'views/account_move_views.xml',
    ],
    'demo': ['demo/demo.xml'],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
