upstream odoo {
    server web:8069;
}
upstream odoochat {
    server web:8072;
}
server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/YOUR_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/YOUR_DOMAIN/privkey.pem;
    location / { proxy_pass http://odoo; }
    location /websocket { proxy_pass http://odoochat; }
}
